/********************************************************************************************************
 * @file    mcu_security.c
 *
 * @brief   This is the header file for BLE SDK
 *
 * @author  BLE GROUP
 * @date    06,2022
 *
 * @par     Copyright (c) 2022, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/
#include "../ext_misc.h"
#include "ext_lib.h"
#include "../../reg_include/soc.h"


//yes is 1, no is 2
enum{
    FLD_BOOT_BRANCH0        =  BIT_RNG(0,1),  //branch 0
    FLD_BOOT_DBG_MODE_DIS   =  BIT_RNG(2,3),  //branch 1, debug mode disable ?
    FLD_BOOT_FLASH_ENC_EN   =  BIT_RNG(4,5),  //branch 2, flash encryption enable ?
    FLD_BOOT_BRANCH3        =  BIT_RNG(6,7),  //branch 3
    FLD_BOOT_BRANCH4        =  BIT_RNG(8,9),  //branch 4
    FLD_BOOT_SECBOOT_EN     =  BIT_RNG(10,11),  //branch 5, secure boot mode ? yes to run mode, no to comp mode
    FLD_BOOT_BRANCH6        =  BIT_RNG(12,13),  //branch 6, comp mode: flash encryption enable ?
    FLD_BOOT_BRANCH7        =  BIT_RNG(14,15),  //branch 7
    FLD_BOOT_BRANCH8        =  BIT_RNG(16,17),  //branch 8, run mode: flash encryption enable ?
    FLD_BOOT_BRANCH9        =  BIT_RNG(18,19),  //branch 9
    FLD_BOOT_BRANCH10       =  BIT_RNG(20,21),  //branch 10
    FLD_BOOT_BRANCH11       =  BIT_RNG(22,23),  //branch 11
    FLD_BOOT_BRANCH12       =  BIT_RNG(24,25),  //branch 12
    FLD_BOOT_BRANCH13       =  BIT_RNG(26,27),  //branch 13, run mode: public key hash match ?
    FLD_BOOT_BRANCH14       =  BIT_RNG(28,29),  //branch 14, run mode: signature pass ?
    FLD_BOOT_BRANCH15       =  BIT_RNG(30,31),  //branch 15

};

/**
 * @brief   flash encrypt and key lock, Byte [2:2]    Bit [22:23]
 */
#define efuse_addr_flash_encrypt_key_lock      2
enum{
    FLD_SEC_FLASH_ENC_EN           = BIT(6),
    FLD_SEC_KEY_LOCK_EN            = BIT(7),
};

/**
 * @brief   pub_key_hash, Byte [73:104]    Bit [584:839]
 *          generated by customer's public key, can be used to verify if public key is OK
 */
#define efuse_addr_pub_key_hash              73
#define EFUSE_BYTE_LEN_PUB_KEY_HASH          32



/**
 * @brief   compatible identifier, Byte [105:108]    Bit [840:871]
 *          [23:22]  fast boot select:
                     2'b00:disable fast boot;
                     2'b01:enable fast boot;
                     2'b10:disable fast boot;
                     2'b11:disable fast boot;
 *          [21]     secure boot mode, 1: secure boot mode, 0: normal mode
 *          [20]     enable_deep_flash_wkup_time
 *          [19:12]  Flash_pwup_time_set: Flash_pwup_time = Flash_pwup_time_set * 50 us
 *          [11:0]:  descriptor flash address = {[11:0] , 12'h0};
 */
#define efuse_addr_desc_flash_addr          105

#define efuse_addr_boot_config              107
enum{
    FLD_SEC_EN_DEPP_FLASH_WKP_TIME  = BIT(4),
    FLD_SEC_SECURE_BOOT             = BIT(5),
    FLD_SEC_FAST_BOOT_BIT0          = BIT(6),  //redundant, if <5> is 1, <6> must be 1
    FLD_SEC_FAST_BOOT_BIT1          = BIT(7),
};





#define DBG_LOG_SECURITY_READ                                   0



_attribute_ble_data_retention_ mcu_secure_t  mcuSecur;

extern drv_api_status_e efuse_read(unsigned char addr, unsigned char* buff, unsigned short len);


bool mcu_security_read_efuse(void)
{
    unsigned char buffer_secure_boot[4];
    unsigned char buffer_flash_encrypt;

    unsigned char i;
    for(i=0;i<3;i++){
        if(efuse_read(efuse_addr_desc_flash_addr, buffer_secure_boot, 4) == DRV_API_SUCCESS && efuse_read(efuse_addr_flash_encrypt_key_lock, &buffer_flash_encrypt, 1) == DRV_API_SUCCESS){ //read success
            break;
        }
    }
    if(i>=3){ //read fail
        //one special case: hardware secure boot used
        mcuSecur.fw_enc_en = 0;
        mcuSecur.secboot_en = 0;

        //tlkapi_send_string_data(DBG_LOG_SECURITY_READ, "[SEC][EFUS] read fail", &i, 1);

        return FALSE;
    }
    else{ //read success
        mcuSecur.fw_enc_en = (buffer_flash_encrypt & FLD_SEC_FLASH_ENC_EN) ? 1 : 0;
        mcuSecur.secboot_en = (buffer_secure_boot[2] & FLD_SEC_SECURE_BOOT) ? 1 : 0;

        /* bit<11:0>, 4K unit
         * even for 16M bit flash, 12bit is enough, maximum value 0xFFF, multiple by 4K, then 0xFFF000
         * we use 12 bit all, to detect some EFUSE error */
        mcuSecur.sb_desc_adr_k = (buffer_secure_boot[1] & 0x0F) << 8 | buffer_secure_boot[0];

        //tlkapi_send_string_data(DBG_LOG_SECURITY_READ, "[SEC][EFUS] read success", buffer, 4);

        return TRUE;
    }
}



bool mcu_security_read_idcode(void)
{

    unsigned char read_err = 0;

    unsigned int idcode_value = reg_boot_idcode(0);//here need to confirm. later todo

    /* debug attention: check if this value only 1 or 2, can never be 0 or 3 */
    unsigned char fw_enc_result = (idcode_value>>4) & 0x03;
    if(fw_enc_result == 1 || fw_enc_result == 2){
        mcuSecur.fw_enc_en = fw_enc_result == 1;
    }
    else{
        read_err = 1;
    }

    unsigned char sec_boot_result = (idcode_value>>10) & 0x03;
    if(sec_boot_result == 1 || sec_boot_result == 2){
        mcuSecur.secboot_en = sec_boot_result == 1;
    }
    else{
        read_err = 1;
    }

    //tlkapi_send_string_u32s(DBG_LOG_SECURITY_READ, "[SEC][IDCD]", idcode_value, fw_enc_result, sec_boot_result, read_err);


    return read_err ? FALSE : TRUE;
}

bool efuse_get_pubkey_hash(u8* pHash)
{
    int i;
    for(i=0;i<3;i++){
        if(efuse_read(efuse_addr_pub_key_hash, pHash, EFUSE_BYTE_LEN_PUB_KEY_HASH) == DRV_API_SUCCESS){ //read success
            break;
        }
    }

    if(i>=3){ //read success
        return TRUE;
    }
    else{ //read fail
        return FALSE;
    }
}
